name: 'new-member-discussions'
description: 'A form to add users to the open, but hidden discussions repository'
title: 'Please add me to the Fresh Eyes Platform: <name>'
labels: ['discussion-user']
assignees:
  - CMIP-IPO
body:

-   type: markdown
    attributes:
        value: |
            ####
            # Request to become a new user. 

            In order to keep our discussions free of spam and unrelated content, we require everyone to be an existing user on GitHub. 
            After filling out this form you will be added to the Fresh Eyes Platform, allowing you to interact the online discussions. Before you join, you much confirm that you have read and agree to abide by the [Platform's Code of Conduct]<https://github.com/Fresh-Eyes-on-CMIP/discussions/blob/0be285fe5bed766dd9f55395870aa2ed63a0ae65/CODE_OF_CONDUCT.md
          
            *The user account you are currently logged on with will be the one that gets registered*
    
-   type: checkboxes
    id: reason
    attributes:
        label: "Do you agree to abide by the Platform Code of Conduct?"
        options: 
            - label: I agree to abide by the Platform Code of Conduct. Please add me to the Fresh Eyes Platform!
            
    validations:
        required: true
