name: Trigger Read Access Dispatch

on:
  issues:
    types: [labeled]

jobs:
  dispatch-event:
    if: github.event.label.name == 'discussion-user'
    runs-on: ubuntu-latest
    steps:
      - name: Get Issue Author
        env:
          ISSUE_NUMBER: "${{ github.event.issue.number }}"
          REPO: "${{ github.repository }}"
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          USERNAME=$(gh api repos/$REPO/issues/$ISSUE_NUMBER --jq .user.login)
          if [[ -z "$USERNAME" ]]; then
            echo "Error: Could not retrieve username from issue."
            exit 1
          fi
          echo "USERNAME=$USERNAME" >> $GITHUB_ENV
      
      - name: Trigger Dispatch in Another Repo
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          TARGET_REPO: "Fresh-Eyes-on-CMIP/discussions"
          USERNAME: "${{ env.USERNAME }}"
        run: |
          gh api repos/$TARGET_REPO/dispatches \
            -f event_type=grant_read_access \
            -f client_payload="{\"username\": \"$USERNAME\"}"
