name: Trigger Read Access Dispatch

on:
  issues:
    types: [opened,labeled]

jobs:
  dispatch-event:
    runs-on: ubuntu-latest
    steps:
      - name: Get username from issue
        run: |
          USERNAME=$(gh api repos/$REPO/issues/$ISSUE_NUMBER --jq .user.login)
          if [[ -z "$USERNAME" ]]; then
            echo "Error: Could not retrieve username from issue."
            exit 1
          fi
          echo "Username retrieved: $USERNAME"
      - name: Dispatch event
        run: |
          RESPONSE=$(gh api -X POST repos/$TARGET_REPO/dispatches --input - <<EOF
          {
            "event_type": "read-access",
            "client_payload": {
              "username": "$USERNAME"
            }
          }
          EOF
          )
          if [[ $? -eq 0 ]]; then
            echo "Dispatch event triggered successfully."
            echo "SUCCESS=true" >> $GITHUB_ENV
          else
            echo "Error triggering dispatch event:"
            echo "$RESPONSE"
            echo "SUCCESS=false" >> $GITHUB_ENV
          fi
